EOS-17389: LR R2: Mini Provisioner - Convert s3_setup to python - config phase <patch 2: Convert config phase from shell to python>         Change description: 	    Pull out the service restart portion in post_install and put then in an external script and execute it before post_install.             Address additional codacy warnings         Added/modified/deleted files: 		modified:   installhelper.sh 		modified:   rpms/s3/s3rpm.spec 		modified:   scripts/provisioning/s3_setup 		modified:   scripts/provisioning/setupcmd.py 		new file:   scripts/s3prov_start_services.sh 	Unit test:             Run "s3_setup config" with these changes and verified steps worked. Performed complete mini-provisioner s3 steps.
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -180,7 +180,14 @@ add_s3backgrounddelete_rabbitmq_user()
 if [ $s3postinstall == true ]
 then
     echo "INFO: Start haproxy, slapd, rabbitmq-server and rsyslog services.."
-    systemctl restart haproxy slapd rabbitmq-server rsyslog
+    sh /opt/seagate/cortx/s3/bin/s3prov_start_services.sh haproxy slapd rabbitmq-server rsyslog
+    if [ $? -eq 0 ]
+    then
+      echo "Services are running successfully."
+    else
+      echo "Failed to start services."
+      exit 1
+    fi
 
     echo "INFO: running post_install..."
     # we already have 'exit' statement in '_s3_setup' binary at failure scenario,
