EOS-15528, EOS-15700: Configure and copy ldap schema in s3_setup provisioning script for single node VM deployment. (#454)
* EOS:15528 Configure and copy ldap schema in s3_setup provisioning script.

ldap replication will also get configured in s3_setup script.
s3:post_install is no-op
s3:config will do ldap and replication configuration
s3:init will create backgrounddelete and recovery accounts.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

reverting rebuildall script changes.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Removed fallback mechanism for ldappassword generation. Also removed enc_ldap_passwd_in_cfg.sh calls.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Reverted changes to jenkins-build script as this lead to failure in s3authserver startup.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Reverting the changes done w.r.t to encryption of ldap password.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Added code changes to read cluster_id and hostnames from confstore.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Removed call to salt cmd from setupReplicationScript.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Incorporated review comments from Ajinkya.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Fixed codacy issue in setupReplicationScript.sh file.

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Fixed s3confstore package as per new changes done to py-utils:confstore

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Added code changes to s3_setup to call "s3confstore --getkey" with delim as '>'

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -32,8 +32,7 @@ USAGE="USAGE: bash $(basename "$0") [--setupjenkinsyumrepo]
                                     [--eesnode2 <Value>]
                                     [--s3backgrounddelete]
                                     [--s3recoverytool]
-                                    [--node1 <Value>]
-                                    [--node2 <Value>]
+                                    [--updateclusterid]
                                     [--createauthjkspassword]
                                     [--cleanup]
                                     [--setlogrotate]
@@ -86,11 +85,25 @@ cleanup_accounts=false
 cleanup_dependencies=false
 setlogrotate=false
 create_auth_jks_passwrd=false
+encrypt_cli="/opt/seagate/cortx/auth/AuthPassEncryptCLI-1.0-0.jar"
 
 if [ $# -lt 1 ]
 then
   echo "$USAGE"
   exit 1
+fi
+
+# check if s3cipher and s3confstore are installed on the system
+if ! command -v s3cipher &>/dev/null
+then
+    echo "ERROR: s3cipher not installed on the system, exiting."
+    exit 1
+fi
+
+if ! command -v s3confstore &>/dev/null
+then
+    echo "ERROR: s3confstore not installed on the system, exiting."
+    exit 1
 fi
 
 while test $# -gt 0
@@ -124,7 +137,7 @@ do
         setup_jenkins_yum_repo=true
         ;;
     --s3backgrounddelete )
-        setup_s3backgrounddelte=true
+        setup_s3backgrounddelete=true
         ;;
     --s3recoverytool )
         setup_s3recoverytool=true
@@ -144,7 +157,10 @@ do
         ;;
     --help | -h )
         echo "$USAGE"
-        exit 1
+        exit 0
+        ;;
+    None )
+        exit 0
         ;;
   esac
   shift
@@ -280,8 +296,11 @@ setup_ldap_replication()
 }
 
 # Fetch and update cluster_id
-fetch_update_cluster_id(){
-    cluster_id=$(salt-call grains.get cluster_id --out=json | jq '.[]') || exit 1
+fetch_update_cluster_id()
+{
+    cluster_id=$(s3confstore --getkey "cluster>cluster_id" --path "json:///opt/seagate/cortx/s3/conf/s3_confstore.json")
+
+    # TODO: remove below sed cmd, as soon as s3backgrounddelete gets updated to read configurations from confstore
     sed -i "s/cluster_id:.*$/cluster_id: "$cluster_id"/g" /opt/seagate/cortx/s3/s3backgrounddelete/s3_cluster.yaml
 }
 
@@ -304,19 +323,27 @@ then
     create_auth_jks_password
 fi
 
+ldappasswd=$(s3cipher --use_base64 --key_len  12  --const_key  openldap 2>/dev/null)
+
 # Install and Configure Openldap over Non-SSL.
-ldappasswd=$(salt-call pillar.get openldap:iam_admin:secret --output=newline_values_only)
-ldappasswd=$(salt-call lyveutil.decrypt openldap ${ldappasswd} --output=newline_values_only)
-
-if [[ -z "$ldappasswd" ]]
-then
-    ldappasswd=ldapadmin
-fi
-
 if [[ $config_ldap == true ]]
 then
-    /opt/seagate/cortx/auth/scripts/enc_ldap_passwd_in_cfg.sh -l $ldappasswd \
-          -p /opt/seagate/cortx/auth/resources/authserver.properties
+    /opt/seagate/cortx/s3/install/ldap/setup_ldap.sh --defaultpasswd --skipssl
+
+    # read host_names from confstore
+    # it will be a comma-separated list of FQDN
+    cluster_hosts=$(s3confstore --getkey "cluster>cluster_hosts" --path "json:///opt/seagate/cortx/s3/conf/s3_confstore.json")
+
+    IFS=','
+    read -ra hosts_arr <<< "$cluster_hosts"
+    if [ ${#hosts_arr[@]} -gt 1 ]
+    then
+        echo "setting ldap-replication on all cluster nodes.."
+        /opt/seagate/cortx/s3/install/ldap/replication/setupReplicationScript.sh -h /root/host_file -p $ldappasswd
+    else
+        echo "INFO: Not setting ldap-replication as 'cluster.cluster_hosts' in confstore has no or only 1 entry."
+    fi
+
     if [[ -f /opt/seagate/cortx/s3/install/ldap/rsyslog.d/slapdlog.conf ]]
     then
         # Enable slapd logging in rsyslog config
@@ -328,9 +355,7 @@ then
 
 elif [[ $purge_config_ldap == true ]]
 then
-    $S3_DIR/scripts/ldap/setup_ldap.sh --defaultpasswd --forceclean --skipssl
-    $S3_DIR/scripts/enc_ldap_passwd_in_cfg.sh -l $ldappasswd \
-          -p /opt/seagate/cortx/auth/resources/authserver.properties
+    /opt/seagate/cortx/s3/install/ldap/setup_ldap.sh --defaultpasswd --forceclean --skipssl
 fi
 
 # Setup Openldap replication for EES setup.
@@ -414,30 +439,14 @@ add_s3backgrounddelete_rabbitmq_user()
 create_s3backgroundelete_keys()
 {
     access_key=$(s3cipher --use_base64 --key_len  22  --const_key  "s3backgroundaccesskey")
-    if [[ $? -ne 0 ]]
-    then
-      access_key=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 22 | head -n 1)
-    fi
     secret_key=$(s3cipher --key_len  40  --const_key  "s3backgroundsecretkey")
-    if [[ $? -ne 0 ]]
-    then
-      secret_key=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9+' | fold -w 40 | head -n 1)
-    fi
 }
 
 # Generate s3recovery keys using cipher
 create_s3recovery_keys()
 {
     access_key=$(s3cipher --use_base64 --key_len  22  --const_key  "s3recoveryaccesskey")
-    if [[ $? -ne 0 ]]
-    then
-      access_key=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 22 | head -n 1)
-    fi
     secret_key=$(s3cipher --key_len  40  --const_key  "s3recoverysecretkey")
-    if [[ $? -ne 0 ]]
-    then
-      secret_key=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9+' | fold -w 40 | head -n 1)
-    fi
 }
 
 # Create s3 account for s3 recoverytool
@@ -448,9 +457,13 @@ create_recovery_tool_account()
     then
       # Create s3recovery tool account
       create_s3recovery_keys
-      salt "*" cmd.run "sed -i \"s/ak:.*/ak: $access_key/g\" /opt/seagate/cortx/s3/install/ldap/s3_recovery_account.ldif"
-      salt "*" cmd.run "sed -i \"s/sk:.*/sk: $secret_key/g\" /opt/seagate/cortx/s3/install/ldap/s3_recovery_account.ldif"
-      salt "*" cmd.run "sed -i \"s/ak=.*/ak=$access_key,ou=accesskeys,dc=s3,dc=seagate,dc=com/g\" /opt/seagate/cortx/s3/install/ldap/s3_recovery_account.ldif"
+      # TODO - use s3confstore to set the access_key and secret_key in confstore.
+      # once the s3recovery is updated to read the keys from confstore, instead of config.yaml file
+      sed -i "s/recovery_account_access_key:.*$/recovery_account_access_key: \"$access_key\"/g" /opt/seagate/cortx/s3/s3backgrounddelete/config.yaml
+      sed -i "s/recovery_account_secret_key:.*$/recovery_account_secret_key: \"$secret_key\"/g" /opt/seagate/cortx/s3/s3backgrounddelete/config.yaml
+      sed -i "s/ak:.*/ak: $access_key/g" /opt/seagate/cortx/s3/install/ldap/s3_recovery_account.ldif
+      sed -i "s/sk:.*/sk: $secret_key/g" /opt/seagate/cortx/s3/install/ldap/s3_recovery_account.ldif
+      sed -i "s/ak=.*/ak=$access_key,ou=accesskeys,dc=s3,dc=seagate,dc=com/g" /opt/seagate/cortx/s3/install/ldap/s3_recovery_account.ldif
       access_key=""
       secret_key=""
       sh /opt/seagate/cortx/s3/install/ldap/create_s3_recovery_account.sh $ldappasswd
@@ -479,11 +492,18 @@ create_background_delete_account()
     output=$(ldapsearch -b "o=s3-background-delete-svc,ou=accounts,dc=s3,dc=seagate,dc=com" -x -w $ldappasswd -D "cn=sgiamadmin,dc=seagate,dc=com" -H ldap://) || echo ""
     if [[ $output == *"No such object"* ]]
     then
-    # Create s3background delete account
+      echo "Setting up rabbitmq server for S3backgroundelete"
+      add_s3backgrounddelete_rabbitmq_user
+
+      # Create s3background delete account
       create_s3backgroundelete_keys
-      salt "*" cmd.run "sed -i \"s/ak:.*/ak: $access_key/g\" /opt/seagate/cortx/s3/install/ldap/background_delete_account.ldif"
-      salt "*" cmd.run "sed -i \"s/sk:.*/sk: $secret_key/g\" /opt/seagate/cortx/s3/install/ldap/background_delete_account.ldif"
-      salt "*" cmd.run "sed -i \"s/ak=.*/ak=$access_key,ou=accesskeys,dc=s3,dc=seagate,dc=com/g\" /opt/seagate/cortx/s3/install/ldap/background_delete_account.ldif"
+      # TODO - use s3confstore to set the access_key and secret_key in confstore.
+      # once the s3backgrounddelete is updated to read the keys from confstore, instead of config.yaml file
+      sed -i "s/background_account_access_key:.*$/background_account_access_key: \"$access_key\"/g" /opt/seagate/cortx/s3/s3backgrounddelete/config.yaml
+      sed -i "s/background_account_secret_key:.*$/background_account_secret_key: \"$secret_key\"/g" /opt/seagate/cortx/s3/s3backgrounddelete/config.yaml
+      sed -i "s/ak:.*/ak: $access_key/g" /opt/seagate/cortx/s3/install/ldap/background_delete_account.ldif
+      sed -i "s/sk:.*/sk: $secret_key/g" /opt/seagate/cortx/s3/install/ldap/background_delete_account.ldif
+      sed -i "s/ak=.*/ak=$access_key,ou=accesskeys,dc=s3,dc=seagate,dc=com/g" /opt/seagate/cortx/s3/install/ldap/background_delete_account.ldif
       access_key=""
       secret_key=""
       sh /opt/seagate/cortx/s3/install/ldap/create_background_delete_account.sh $ldappasswd
@@ -506,10 +526,8 @@ delete_background_delete_account()
 }
 
 # Setup s3 background delete and its dependencies
-if [[ $setup_s3backgrounddelte == true ]]
+if [[ $setup_s3backgrounddelete == true ]]
 then
-    echo "Setting up rabbitmq server for S3backgroundelete"
-    add_s3backgrounddelete_rabbitmq_user
     echo "Creating the s3backgrounddelete account"
     create_background_delete_account
 fi
@@ -586,10 +604,17 @@ get_platform() {
 
 if [[ $setlogrotate == true ]]
 then
-    plt=$(get_platform)
-    echo "Server type is $plt"
-    if [[ "$plt" == "virtual" ]]
-    then
-        set_logrotate_policy_ova
-    fi
+    set_logrotate_policy_ova
 fi
+
+# TODO - uncomment below section once we know how to figure out the host type (virtual or physical)
+# without using 'provisioner' cli.
+#if [[ $setlogrotate == true ]]
+#then
+#    plt=$(get_platform)
+#    echo "Server type is $plt"
+#    if [[ "$plt" == "virtual" ]]
+#    then
+#        set_logrotate_policy_ova
+#    fi
+#fi
