Incorporated review comments from Basav.
Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -241,9 +241,14 @@ fetch_update_cluster_id()
         exit 1
     fi
     cluster_id=$(s3confstore --getkey "cluster>cluster_id" --path "$confstore_config_url")
-
-    # TODO: remove below sed cmd, as soon as s3backgrounddelete gets updated to read configurations from confstore
-    sed -i "s/cluster_id:.*$/cluster_id: "$cluster_id"/g" /opt/seagate/cortx/s3/s3backgrounddelete/s3_cluster.yaml
+    if [ $? -eq 0 ]
+    then
+        # TODO: remove below sed cmd, as soon as s3backgrounddelete gets updated to read configurations from confstore
+        sed -i "s/cluster_id:.*$/cluster_id: "$cluster_id"/g" /opt/seagate/cortx/s3/s3backgrounddelete/s3_cluster.yaml
+    else
+        echo "ERROR: failed to read cluster>cluster_id from py-utils:confstore, exiting."
+        exit 1
+    fi
 }
 
 # Fetch and update cluster id
@@ -279,7 +284,13 @@ then
         for ((index=0; index<"$server_nodes_count"; index++))
         do
             host=$(s3confstore --getkey "cluster>server["$index"]>hostname" --path "$confstore_config_url")
-            echo "$host" >> hosts_list_file.txt
+            if [ $? -eq 0 ]
+            then
+                echo "$host" >> hosts_list_file.txt
+            else
+                echo "ERROR: failed to read cluster>server[$index]>hostname from py-utils:confstore, exiting."
+                exit 1
+            fi
         done
         echo "setting ldap-replication on all cluster nodes.."
         /opt/seagate/cortx/s3/install/ldap/replication/setupReplicationScript.sh -h hosts_list_file.txt -p "$ldappasswd"
