EOS-15530 : LDRr2: Configure HAProxy as a part of S3 setup component provisioning (#615)
* EOS-15530: Configure HAProxy as a part of S3 setup mini provisioner

    Problem: The process to setup HAProxy is manual, add these steps via python script

    Solution: s3_haproxy_config.py now does all the relevant steps

    Testing: executed s3_haproxy_config binary and checked haproxy.cfg file

    Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>

* Problem: The process to setup HAProxy is manual, add these steps via python script

    Solution: s3_haproxy_config.py now does all the relevant steps

    Testing: executed s3_haproxy_config binary and checked haproxy.cfg file

    Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>

* EOS-15530 : LDRr2: Configure HAProxy

    Solution: s3_haproxy_config.py now does all the relevant steps

    Testing: executed s3_haproxy_config binary and checked haproxy.cfg file

    Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>

* Problem: The process to setup HAProxy is manual, add these steps via python script

    Solution: s3_haproxy_config.py now does all the relevant steps

    Testing: executed s3_haproxy_config binary and checked haproxy.cfg file

    Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>

* EOS-15530 : LDRr2: Configure HAProxy

        Problem: The process to setup HAProxy is manual, add these steps via python script

        Solution: s3_haproxy_config.py now does all the relevant steps

        Testing: executed s3_haproxy_config binary and checked haproxy.cfg file

        Signed-off-by: Mohammed Shahid <mohammed.shahid@seagate.com>

* Fixed s3_setup script to pass confstore path to s3haproxyconfig cli and added argparse logic in s3_haproxy_config.py

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

* Fix : Check if directory exists before creating.

Signed-off-by: “Mohammed <mohammed.shahid@seagate.com>

Co-authored-by: root <root@ssc-vm-c-1560.colo.seagate.com>
Co-authored-by: Amit Kumar <amit.kumar@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -28,6 +28,7 @@ USAGE="USAGE: bash $(basename "$0") [--setupjenkinsyumrepo]
                                     [--confurl <URL_PATH>]
                                     [--s3backgrounddelete]
                                     [--s3recoverytool]
+                                    [--confighaproxy]
                                     [--updateclusterid]
                                     [--createauthjkspassword]
                                     [--cleanup]
@@ -43,6 +44,7 @@ where:
 --ldapreplication        Setup LDAP replication
 --s3backgrounddelete     Configure s3backgrounddelete and its dependencies
 --s3recoverytool         Configure s3recoverytool and its dependencies
+--confighaproxy          Configure haproxy
 --updateclusterid        Fetch and update cluster id in S3 config
 --cleanup                Cleanup S3 accounts created for backgroundelete.
 --createauthjkspassword  Setup random jks password for Auth server
@@ -115,6 +117,9 @@ do
         ;;
     --s3recoverytool )
         setup_s3recoverytool=true
+        ;;
+    --confighaproxy )
+        setup_s3haproxyconfig=true
         ;;
     --updateclusterid )
         update_cluster_id=true
@@ -477,6 +482,18 @@ if [[ $setup_s3recoverytool == true ]]
 then
     echo "Creating the s3 recovery tool account"
 	create_recovery_tool_account
+fi
+
+# Configure haproxy
+if [[ $setup_s3haproxyconfig == true ]]
+then
+    echo "Configuring haproxy.."
+	s3haproxyconfig --path "$confstore_config_url"
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR: haproxy configuration failed, exiting"
+        exit 1
+    fi
 fi
 
 # Clean up backgrounddelete account
