Fixed s3_setup script to read cluster hosts as per new changes done in confstore.
Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -62,6 +62,7 @@ major_version=`echo ${VERSION} | awk -F '.' '{ print $1 }'`
 selinux_status=$(sestatus| grep -w "SELinux status" | cut -d ':' -f 2  | xargs)
 
 confstore_config_url=
+confstore_config_url_set=false
 post_dependency=false
 purge_config_ldap=false
 config_ldap=false
@@ -109,6 +110,7 @@ do
         ;;
     --confurl ) shift;
         confstore_config_url=$1
+        confstore_config_url_set=true
         ;;
     --setupjenkinsyumrepo )
         setup_jenkins_yum_repo=true
@@ -143,7 +145,7 @@ do
   shift
 done
 
-if [ -z "$confstore_config_url"]
+if [ $confstore_config_url_set == true ] && [ -z "$confstore_config_url" ]
 then
     echo "ERROR: confstore_config_url is empty, exiting."
     exit 1
@@ -233,6 +235,11 @@ fi
 # Fetch and update cluster_id
 fetch_update_cluster_id()
 {
+    if [ ! -z '$confstore_config_url' ]
+    then
+        echo "ERROR: confstore config file URL is not set, cannot use confstore, exiting."
+        exit 1
+    fi
     cluster_id=$(s3confstore --getkey "cluster>cluster_id" --path "$confstore_config_url")
 
     # TODO: remove below sed cmd, as soon as s3backgrounddelete gets updated to read configurations from confstore
@@ -265,18 +272,20 @@ if [[ $config_ldap == true ]]
 then
     /opt/seagate/cortx/s3/install/ldap/setup_ldap.sh --defaultpasswd --skipssl
 
-    # read host_names from confstore
-    # it will be a comma-separated list of FQDN
-    cluster_hosts=$(s3confstore --getkey "cluster>cluster_hosts" --path "$confstore_config_url")
-
-    IFS=','
-    read -ra hosts_arr <<< "$cluster_hosts"
-    if [ ${#hosts_arr[@]} -gt 1 ]
+    # check number of nodes in the cluster
+    server_nodes_count=$(s3confstore --getkey "cluster>node_count" --path "$confstore_config_url")
+    if [ "$server_nodes_count" -gt 1 ]
     then
+        for ((index=0; index<"$server_nodes_count"; index++))
+        do
+            host=$(s3confstore --getkey "cluster>server["$index"]>hostname" --path "$confstore_config_url")
+            echo "$host" >> hosts_list_file.txt
+        done
         echo "setting ldap-replication on all cluster nodes.."
-        /opt/seagate/cortx/s3/install/ldap/replication/setupReplicationScript.sh -h "$cluster_hosts" -p "$ldappasswd"
+        /opt/seagate/cortx/s3/install/ldap/replication/setupReplicationScript.sh -h hosts_list_file.txt -p "$ldappasswd"
+        rm -f hosts_list_file.txt
     else
-        echo "INFO: Not setting ldap-replication as 'cluster>cluster_hosts' in confstore has no or only 1 entry."
+        echo "INFO: Not setting ldap-replication as 'cluster>node_count' is less than 2."
     fi
 
     if [[ -f /opt/seagate/cortx/s3/install/ldap/rsyslog.d/slapdlog.conf ]]
