EOS:16672 - Consolidated current cmdline arguments of 's3_setup' into options mandated by provisioner.
Only following options would be supported by each component provisioner script:

post_install
config
init
cleanup
rest
upgrade
backup
restore
test
support_bundle

Signed-off-by: Amit Kumar <amit.kumar@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -19,62 +19,47 @@
 #
 
 #######################################################
-# Install and configure release S3Server installation #
+# Configure and initialize s3server and dependencies
 #######################################################
-USAGE="USAGE: bash $(basename "$0") [--setupjenkinsyumrepo]
-                                    [--postdependency]
-                                    [--purgeconfigldap]
-                                    [--configldap]
-                                    [--confurl <URL_PATH>]
-                                    [--s3backgrounddelete]
-                                    [--s3recoverytool]
-                                    [--confighaproxy]
-                                    [--updateclusterid]
-                                    [--createauthjkspassword]
-                                    [--cleanup]
-                                    [--help | -h]
-Install and configure release S3server setup.
+USAGE="USAGE: bash $(basename "$0") [post_install]
+                    [config]
+                    [init]
+                    [cleanup]
+                    --config <confstore-config-file-url-path>
 
 where:
---setupjenkinsyumrepo    Setup required S3 yum repos.
---postdependency         Configure S3server post installation of dependencies.
---purgeconfigldap        Clear and Setup all LDAP configs
---configldap             Setup all LDAP configs
---confurl                configuration file url, for using with py-utils:ConfStore
---ldapreplication        Setup LDAP replication
---s3backgrounddelete     Configure s3backgrounddelete and its dependencies
---s3recoverytool         Configure s3recoverytool and its dependencies
---confighaproxy          Configure haproxy
---updateclusterid        Fetch and update cluster id in S3 config
---cleanup                Cleanup S3 accounts created for backgroundelete.
---createauthjkspassword  Setup random jks password for Auth server
+post_install             will do postinstall steps, which will include validation of
+                         pre-requisite packages and services, like motr
+
+config                   do configuration of openldap (with replicstion), haproxy and
+                         create authjks keys.
+
+init                     create s3backgrounddelete, s3recoverytool s3 accounts
+
+cleanup                  cleanup S3 accounts created for backgrounddelete service and recovery tool
+
+--config                 URL path for the confstore configuration file. This option is Mandatory
+
 --help                   Display this help and exit"
 
 set -e
 
-S3_DIR="/root/s3server"
 access_key=""
 secret_key=""
 
-OS=$(cat /etc/os-release | grep -w ID | cut -d '=' -f 2)
-VERSION=`cat /etc/os-release | sed -n 's/VERSION_ID=\"\([0-9].*\)\"/\1/p'`
-major_version=`echo ${VERSION} | awk -F '.' '{ print $1 }'`
-selinux_status=$(sestatus| grep -w "SELinux status" | cut -d ':' -f 2  | xargs)
+confstore_config_url=""
+s3postinstall=false
+s3config=false
+s3init=false
+s3cleanup=false
 
-confstore_config_url=
-post_dependency=false
-purge_config_ldap=false
-config_ldap=false
-setup_jenkins_yum_repo=false
-setup_s3backgrounddelete=false
-setup_s3recoverytool=false
-update_cluster_id=false
-is_rabbitmq_clustered=false
-cleanup_s3_accounts_schema=false
-create_auth_jks_passwrd=false
+cipherkey=""
+sgiamadminpassd=""
+ldappasswd=""
+
 encrypt_cli="/opt/seagate/cortx/auth/AuthPassEncryptCLI-1.0-0.jar"
 
-if [ $# -lt 1 ]
+if [ $# -lt 3 ]
 then
   echo "$USAGE"
   exit 1
@@ -103,38 +88,20 @@ fi
 while test $# -gt 0
 do
   case "$1" in
-    --postdependency )
-        post_dependency=true
+    post_install )
+        s3postinstall=true
         ;;
-    --configldap )
-        config_ldap=true
+    config )
+        s3config=true
         ;;
-    --purgeconfigldap )
-        purge_config_ldap=true
+    init )
+        s3init=true
         ;;
-    --confurl ) shift;
+    cleanup )
+        s3cleanup=true
+        ;;
+    --config ) shift;
         confstore_config_url=$1
-        ;;
-    --setupjenkinsyumrepo )
-        setup_jenkins_yum_repo=true
-        ;;
-    --s3backgrounddelete )
-        setup_s3backgrounddelete=true
-        ;;
-    --s3recoverytool )
-        setup_s3recoverytool=true
-        ;;
-    --confighaproxy )
-        setup_s3haproxyconfig=true
-        ;;
-    --updateclusterid )
-        update_cluster_id=true
-        ;;
-    --cleanup )
-        cleanup_s3_accounts_schema=true
-        ;;
-    --createauthjkspassword )
-        create_auth_jks_passwrd=true
         ;;
     --help | -h )
         echo "$USAGE"
@@ -147,98 +114,30 @@ do
   shift
 done
 
-echo "INFO: confstore URL path: $confstore_config_url"
-
-setup_release_repo()
-{
-cat >/etc/yum.repos.d/releases_cortx_lustre.repo <<EOL
-[releases_cortx_lustre]
-baseurl = http://cortx-storage.colo.seagate.com/releases/cortx/github/release/rhel-7.7.1908/last_successful/
-gpgcheck = 0
-name = Yum repo for lustre
-priority = 1
-EOL
-
-cat >/etc/yum.repos.d/releases_cortx_hare.repo <<EOL
-[releases_cortx_hare]
-baseurl = http://cortx-storage.colo.seagate.com/releases/cortx/github/release/rhel-7.7.1908/last_successful/
-gpgcheck = 0
-name = Yum repo for hare
-priority = 1
-EOL
-
-cat >/etc/yum.repos.d/releases_cortx_motr.repo <<EOL
-[releases_cortx_motr]
-baseurl = http://cortx-storage.colo.seagate.com/releases/cortx/components/github/dev/rhel-7.7.1908/dev/motr/last_successful/
-gpgcheck = 0
-name = Yum repo for motr
-priority = 1
-EOL
-
-cat >/etc/yum.repos.d/releases_cortx_s3server.repo <<EOL
-[releases_cortx_s3server]
-baseurl = http://cortx-storage.colo.seagate.com/releases/cortx/components/dev/centos-7.7.1908/s3server/last_successful/
-gpgcheck = 0
-name = Yum repo for s3server
-priority = 1
-EOL
-
-if [ "$major_version" = "7" ];
+if [ -z "$confstore_config_url" ]
 then
-
-cat >/etc/yum.repos.d/releases_s3server_uploads <<EOL
-[releases_s3server_uploads]
-baseurl = http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-7.7.1908/s3server_uploads/
-gpgcheck = 0
-name = Yum repo for S3 server dependencies
-priority = 1
-EOL
-
-cat >/etc/yum.repos.d/prvsnr_local_repository <<EOL
-[prvsnr_local_repository]
-baseurl = http://cortx-storage.colo.seagate.com/prvsnr/vendor/centos/epel/
-gpgcheck = 0
-name = Yum local repo for S3 server dependencies
-priority = 1
-EOL
-
-elif [ "$major_version" = "8" ];
-then
-cat >/etc/yum.repos.d/releases_s3server_uploads <<EOL
-[releases_s3server_uploads]
-baseurl = http://cortx-storage.colo.seagate.com/releases/cortx/uploads/centos/centos-8.0.1905/s3server_uploads/
-gpgcheck = 0
-name = Yum repo for S3 server dependencies
-priority = 1
-EOL
-
-# TODO Change it from public to mirror repo, once available
-cat >/etc/yum.repos.d/prvsnr_local_repository <<EOL
-[prvsnr_local_repository]
-baseurl = http://dl.fedoraproject.org/pub/epel/8/Everything/x86_64/
-gpgcheck = 0
-name = Yum local repo for S3 server dependencies
-priority = 1
-EOL
-
+    echo "ERROR: --config option is mandatory and value should be a valid URL path, exiting"
+    exit 1
 fi
+
+
+get_ldap_password()
+{
+    cipherkey=$(s3cipher --generate_key --const_key  openldap 2>/dev/null)
+    sgiamadminpassd=$(s3confstore "$confstore_config_url" getkey --key "openldap>sgiam>secret")
+    # decrypt the password read from the confstore
+    ldappasswd=$(s3cipher --decrypt --data $sgiamadminpassd --key $cipherkey 2>/dev/null)
 }
 
-# Setup required S3 repos for S3 dependencies.
-if [[ $setup_jenkins_yum_repo == true ]]
-then
-setup_release_repo
-fi
+# get openldap password from confstore
+echo "Get openldap passwords from confstore.."
+get_ldap_password
+
 
 # Fetch and update cluster_id
 fetch_update_cluster_id()
 {
-    if [ -z "$confstore_config_url" ]
-    then
-        echo "ERROR: confstore config file URL is not set, cannot use confstore, exiting."
-        exit 1
-    fi
-    cluster_id=$(s3confstore --getkey "cluster>cluster_id" --path "$confstore_config_url")
+    cluster_id=$(s3confstore "$confstore_config_url" getkey --key "cluster>cluster_id")
     if [ $? -eq 0 ]
     then
         # TODO: remove below sed cmd, as soon as s3backgrounddelete gets updated to read configurations from confstore
@@ -249,49 +148,80 @@ fetch_update_cluster_id()
     fi
 }
 
-# Fetch and update cluster id
-if [[ $update_cluster_id == true ]]
-then
-    echo "Fetching and updating cluster id in s3_cluster.yaml"
-    fetch_update_cluster_id
-fi
-
-# Create random password for auth jks keystore
-create_auth_jks_password(){
+create_auth_jks_password()
+{
     sh /opt/seagate/cortx/auth/scripts/create_auth_jks_password.sh
 }
 
-# Setup random jks password for authserver
-if [[ $create_auth_jks_passwrd == true ]]
+if [ $s3postinstall == true ]
 then
-    echo "Creating random jks password for Auth server"
-    create_auth_jks_password
+    echo "INFO: running post_install..."
+    # exit 0
 fi
 
-cipherkey=$(s3cipher --generate_key --const_key  openldap 2>/dev/null)
-sgiamadminpassd=$(s3confstore --getkey "cluster>openldap>sgiampassword" --path "$confstore_config_url")
-# decrypt the password read from the confstore
-ldappasswd=$(s3cipher --decrypt --data $sgiamadminpassd --key $cipherkey 2>/dev/null)
+if [ $s3config == true ]
+then
+    # Fetch and update cluster id
+    echo "INFO: Fetching and updating cluster id in s3_cluster.yaml .."
+    fetch_update_cluster_id
+
+    # Create random password for auth jks keystore
+    echo "INFO: Creating random jks password for Auth server.."
+    create_auth_jks_password
+
+    # configure openldap and ldap-replication
+    echo "INFO: Configure openldap.."
+    configure_openldap()
+
+    echo "INFO: Configure haproxy.."
+	s3haproxyconfig --path "$confstore_config_url"
+    if [ $? -ne 0 ]
+    then
+        echo "ERROR: haproxy configuration failed, exiting"
+        exit 1
+    fi
+
+fi
+
+if [ $s3init == true ]
+then
+    # Setup s3 background delete and its dependencies
+    echo "INFO: Creating the s3backgrounddelete account.."
+    create_background_delete_account
+
+    # Setup recovery tool dependancies
+    echo "INFO: Creating the s3 recovery tool account"
+	create_recovery_tool_account
+
+    # set logrotate policy
+    plat=$(s3confstore "$confstore_config_url" getkey --key "cluster>env_type")
+    echo "INFO: cluster environment type: $plat"
+    if [ "$plat" == "VM" ]
+    then
+        echo "INFO: setting logrotate policy.."
+        set_logrotate_policy_ova
+    fi
+fi
+
+if [ $s3cleanup == true ]
+then
+    s3setup --cleanup accounts --ldappasswd $ldappasswd
+fi
 
 # Install and Configure Openldap over Non-SSL.
-if [[ $config_ldap == true ]]
-then
+configure_openldap()
+{
     /opt/seagate/cortx/s3/install/ldap/setup_ldap.sh --confurl "$confstore_config_url" --defaultpasswd --skipssl
 
     # check number of nodes in the cluster
-    server_nodes_count=$(s3confstore --getkey "cluster>node_count" --path "$confstore_config_url")
+    server_nodes_count=$(s3confstore "$confstore_config_url" getnodecount)
     if [ "$server_nodes_count" -gt 1 ]
     then
-        for ((index=0; index<"$server_nodes_count"; index++))
+        hosts_str=$(s3confstore "$confstore_config_url" getnodenames)
+        read -ra hosts_arr <<< "$hosts_str"
+        for host in "${hosts_arr[@]}"
         do
-            host=$(s3confstore --getkey "cluster>server["$index"]>hostname" --path "$confstore_config_url")
-            if [ $? -eq 0 ]
-            then
-                echo "$host" >> hosts_list_file.txt
-            else
-                echo "ERROR: failed to read cluster>server[$index]>hostname from py-utils:confstore, exiting."
-                exit 1
-            fi
+            host >> hosts_list_file.txt
         done
         echo "setting ldap-replication on all cluster nodes.."
         /opt/seagate/cortx/s3/install/ldap/replication/setupReplicationScript.sh -h hosts_list_file.txt -p "$ldappasswd"
@@ -308,70 +238,14 @@ then
     fi
     systemctl restart s3authserver
     systemctl restart rsyslog
-
-elif [[ $purge_config_ldap == true ]]
-then
-    /opt/seagate/cortx/s3/install/ldap/setup_ldap.sh --defaultpasswd --forceclean --skipssl
-fi
-
-# Post S3 dependency installation steps for configuring S3.
-if [[ $post_dependency == true ]]
-then
-    rpm -q openssl java-1.8.0-openjdk-headless redis haproxy keepalived rsyslog stx-s3-certs stx-s3-client-certs|| exit 1
-    # Copy haproxy config and rsyslog dependencies
-    if [ "$major_version" = "7" ];
-    then
-        cp /opt/seagate/cortx/s3/install/haproxy/haproxy_osver7.cfg /etc/haproxy/haproxy.cfg
-    elif [ "$major_version" = "8" ];
-    then
-        cp /opt/seagate/cortx/s3/install/haproxy/haproxy_osver8.cfg /etc/haproxy/haproxy.cfg
-    fi
-
-    cp /opt/seagate/cortx/s3/install/haproxy/503.http /etc/haproxy/errors/
-    cp /opt/seagate/cortx/s3/install/haproxy/logrotate/haproxy /etc/logrotate.d/haproxy
-    cp /opt/seagate/cortx/s3/install/haproxy/rsyslog.d/haproxy.conf /etc/rsyslog.d/haproxy.conf
-
-    if [ -f /etc/cron.daily/logrotate ];
-    then
-        rm -rf /etc/cron.daily/logrotate
-    fi
-
-    cp /opt/seagate/cortx/s3/install/haproxy/logrotate/logrotate /etc/cron.hourly/logrotate
-
-    # Enable slapd logging in rsyslog config
-    cp /opt/seagate/cortx/s3/install/ldap/rsyslog.d/slapdlog.conf /etc/rsyslog.d/slapdlog.conf
-
-    if [ "$selinux_status" = "enabled" ];
-    then
-        setsebool httpd_can_network_connect on -P
-        setsebool haproxy_connect_any 1 -P
-    fi
-
-    mkdir -p /var/seagate/s3
-
-    # Update python36 symlinks
-    if ! command -v python36 &>/dev/null;
-    then
-      if command -v python3.6 &>/dev/null;
-      then
-        ln -s "`command -v python3.6`" /usr/bin/python36
-      else
-        echo "Python v3.6 is not installed (neither python36 nor python3.6 are found in PATH)."
-        exit 1
-      fi
-    fi
-
-    systemctl restart slapd
-    systemctl restart rsyslog
-
-fi
+}
 
 add_s3backgrounddelete_rabbitmq_user()
 {
     users=`rabbitmqctl list_users`
     if [[ $users =~ "cortx-s3" ]]
     then
-    echo "Rabbitmq s3user already exists. Cleaning existing s3user."
+    echo "WARN: Rabbitmq s3user already exists. Cleaning existing s3user."
     rabbitmqctl delete_user cortx-s3
     fi
     # Create a user (In this case user is 'cortx-s3' with password as 'password')
@@ -382,7 +256,7 @@ add_s3backgrounddelete_rabbitmq_user()
     # Setup queue mirroring
     rabbitmqctl set_policy ha-all ".*" '{"ha-mode":"all"}'
 
-    echo "Rabbitmq configuration for this node is completed..."
+    echo "INFO: Rabbitmq configuration for this node is completed..."
 }
 
 # Generate s3backgroundelete keys using cipher
@@ -423,19 +297,6 @@ create_recovery_tool_account()
     fi
 }
 
-# Delete s3 account which was used by s3recoverytool
-delete_recovery_tool_account()
-{
-    output=$(ldapsearch -b "o=s3-recovery-svc,ou=accounts,dc=s3,dc=seagate,dc=com" -x -w $ldappasswd -D "cn=sgiamadmin,dc=seagate,dc=com" -H ldap://) || echo ""
-    if [[ $output != *"No such object"* ]]
-    then
-    # Delete s3recovery tool account
-      sh /opt/seagate/cortx/s3/install/ldap/delete_s3_recovery_account.sh $ldappasswd
-      echo "Deleted s3recovery tool account successfully..."
-	fi
-}
-
-
 # Create s3 account for s3 backgrounddelete
 create_background_delete_account()
 {
@@ -463,50 +324,6 @@ create_background_delete_account()
     fi
 }
 
-# Delete s3 account which was used by s3background delete
-delete_background_delete_account()
-{
-    output=$(ldapsearch -b "o=s3-background-delete-svc,ou=accounts,dc=s3,dc=seagate,dc=com" -x -w $ldappasswd -D "cn=sgiamadmin,dc=seagate,dc=com" -H ldap://) || echo ""
-    if [[ $output != *"No such object"* ]]
-    then
-	   # Delete s3background delete account
-	   sh /opt/seagate/cortx/s3/install/ldap/delete_background_delete_account.sh $ldappasswd
-	   echo "Deleted s3backgrounddelete account successfully..."
-	fi
-}
-
-# Setup s3 background delete and its dependencies
-if [[ $setup_s3backgrounddelete == true ]]
-then
-    echo "Creating the s3backgrounddelete account"
-    create_background_delete_account
-fi
-
-# Setup recovery tool dependancies
-if [[ $setup_s3recoverytool == true ]]
-then
-    echo "Creating the s3 recovery tool account"
-	create_recovery_tool_account
-fi
-
-# Configure haproxy
-if [[ $setup_s3haproxyconfig == true ]]
-then
-    echo "Configuring haproxy.."
-	s3haproxyconfig --path "$confstore_config_url"
-    if [ $? -ne 0 ]
-    then
-        echo "ERROR: haproxy configuration failed, exiting"
-        exit 1
-    fi
-fi
-
-# Clean up backgrounddelete account
-if [[ $cleanup_s3_accounts_schema == true ]]
-then
-    s3setup --cleanup accounts --ldappasswd $ldappasswd
-fi
-
 set_logrotate() {
     fname=$1
     set_sz=$2
@@ -514,6 +331,19 @@ set_logrotate() {
 
     sed -i "s/rotate [0-9]*/rotate $set_fcount/" $fname
     sed -i "s/size [0-9bBkKmMgGpPtT]*/size $set_sz/" $fname
+}
+
+set_logrotate_policy_ova() {
+    lgrtd="/etc/logrotate.d/haproxy
+           /etc/logrotate.d/openldap
+           /etc/logrotate.d/s3auditlog"
+
+    for f in $lgrtd
+    do
+        set_logrotate $f 1M 5
+    done
+
+    set_s3conf_log_sz 5
 }
 
 set_s3conf_log_sz() {
