EOS-15971: Modify s3_setup shell script to Python - Cleanup util             Change description: 		Address Ajinkya's and Amit's review comments from PR             List of files: 		modified:   rpms/s3/s3rpm.spec 		deleted:    s3psetup/clean_open_ldap_by_s3.sh 		deleted:    s3psetup/s3psetup/s3psetup 		modified:   scripts/provisioning/s3_setup 		renamed:    s3psetup/README.md -> scripts/provisioning/s3setup/README.md 		renamed:    s3psetup/VERSION -> scripts/provisioning/s3setup/VERSION 		new file:   scripts/provisioning/s3setup/clean_open_ldap_by_s3.sh 		renamed:    s3psetup/s3psetup/__init__.py -> scripts/provisioning/s3setup/s3setup/__init__.py 		renamed:    s3psetup/s3psetup/cortx_s3_py_setup.py -> scripts/provisioning/s3setup/s3setup/cortx_s3_setup.py 		new file:   scripts/provisioning/s3setup/s3setup/s3setup 		renamed:    s3psetup/setup.py -> scripts/provisioning/s3setup/setup.py 		renamed:    s3psetup/test_s3_setup.sh -> scripts/provisioning/s3setup/test_s3_setup.sh
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -70,9 +70,7 @@ setup_s3backgrounddelete=false
 setup_s3recoverytool=false
 update_cluster_id=false
 is_rabbitmq_clustered=false
-cleanup_accounts=false
-cleanup_dependencies=false
-cleanup_both=false
+cleanup_s3_accounts_schema=false
 setlogrotate=false
 create_auth_jks_passwrd=false
 encrypt_cli="/opt/seagate/cortx/auth/AuthPassEncryptCLI-1.0-0.jar"
@@ -83,7 +81,7 @@ then
   exit 1
 fi
 
-# check if s3cipher, s3confstore and s3psetup are installed on the system
+# check if s3cipher, s3confstore and s3setup are installed on the system
 if ! command -v s3cipher &>/dev/null
 then
     echo "ERROR: s3cipher not installed on the system, exiting."
@@ -96,9 +94,9 @@ then
     exit 1
 fi
 
-if ! command -v s3psetup &>/dev/null
+if ! command -v s3setup &>/dev/null
 then
-    echo "ERROR: s3psetup not installed on the system, exiting."
+    echo "ERROR: s3setup not installed on the system, exiting."
     exit 1
 fi
 
@@ -134,9 +132,7 @@ do
         update_cluster_id=true
         ;;
     --cleanup )
-        # cleanup_accounts=true
-        # cleanup_dependencies=true
-        cleanup_both=true
+        cleanup_s3_accounts_schema=true
         ;;
     --createauthjkspassword )
         create_auth_jks_passwrd=true
@@ -507,32 +503,9 @@ then
 fi
 
 # Clean up backgrounddelete account
-if [[ $cleanup_both == true ]]
+if [[ $cleanup_s3_accounts_schema == true ]]
 then
-    s3psetup --cleanup accounts
-    # Using both causes the config files to be removed and
-    # this will impact idempotency
-    # s3psetup --cleanup both
-fi
-
-# Clean up backgrounddelete account
-if [[ $cleanup_accounts == true ]]
-then
-    echo "Deleting the s3background delete account"
-    delete_background_delete_account
-    echo "Deleting the s3recovery tool account"
-	delete_recovery_tool_account
-fi
-
-# Clean up s3 dependencies
-if [[ $cleanup_dependencies == true ]]
-then
-    echo "removing s3 dependencies"
-    yum -y remove log4cxx_cortx || echo ""
-    mv -f /opt/seagate/cortx/auth/resources/authserver.properties /opt/seagate/cortx/auth/resources/authserver.properties.bak
-    mv -f /opt/seagate/cortx/s3/s3backgrounddelete/config.yaml /opt/seagate/cortx/s3/s3backgrounddelete/config.yaml.bak
-    mv -f /opt/seagate/cortx/auth/resources/keystore.properties /opt/seagate/cortx/auth/resources/keystore.properties.bak
-    mv -f /opt/seagate/cortx/s3/conf/s3config.yaml /opt/seagate/cortx/s3/conf/s3config.yaml.bak
+    s3setup --cleanup accounts
 fi
 
 set_logrotate() {
