EOS-15971: Modify s3_setup shell script to Python - Cleanup util         Change description:           1. Integrate the newly added s3psetup with build system so that s3server's rpm will contain this program.           2. Integrate s3psetup with s3_setup only for cleanup operation. Note to reviewers: Dependency cleanup causes config files to be removed. This causes additional problems to the expected idempotency nature of the control flow in s3-setup. Hence dependency cleanup is temporarily disabled in s3_setup.           3. Update s3psetup, bug fixes found during unit tests, log addition, use optional ldappasswd etc.           4. Add sample test scripts used to unit test this change. These scripts also contain additional steps so that s3_cleanup can run again and again w/o any failures. (ref. clean_open_ldap_by_s3.sh, prerequisite to test_s3_setup.sh)         List of files: 		modified:   rpms/s3/s3rpm.spec 		modified:   s3psetup/README.md 		modified:   s3psetup/s3psetup/cortx_s3_py_setup.py 		modified:   scripts/provisioning/s3_setup 		new file:   clean_open_ldap_by_s3.sh 		new file:   test_s3_setup.sh         Testing:         UT:           On single node VM, based on the steps provided by Amit, created test_s3_setup.sh and ran it multiple times with this rpm. Added debug logs were also checked to confirm there were no failures.
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -72,6 +72,8 @@ update_cluster_id=false
 is_rabbitmq_clustered=false
 cleanup_accounts=false
 cleanup_dependencies=false
+cleanup_both=false
+setlogrotate=false
 create_auth_jks_passwrd=false
 encrypt_cli="/opt/seagate/cortx/auth/AuthPassEncryptCLI-1.0-0.jar"
 
@@ -81,7 +83,7 @@ then
   exit 1
 fi
 
-# check if s3cipher and s3confstore are installed on the system
+# check if s3cipher, s3confstore and s3psetup are installed on the system
 if ! command -v s3cipher &>/dev/null
 then
     echo "ERROR: s3cipher not installed on the system, exiting."
@@ -93,6 +95,13 @@ then
     echo "ERROR: s3confstore not installed on the system, exiting."
     exit 1
 fi
+
+if ! command -v s3psetup &>/dev/null
+then
+    echo "ERROR: s3psetup not installed on the system, exiting."
+    exit 1
+fi
+
 
 while test $# -gt 0
 do
@@ -125,8 +134,9 @@ do
         update_cluster_id=true
         ;;
     --cleanup )
-        cleanup_accounts=true
-        cleanup_dependencies=true
+        # cleanup_accounts=true
+        # cleanup_dependencies=true
+        cleanup_both=true
         ;;
     --createauthjkspassword )
         create_auth_jks_passwrd=true
@@ -494,6 +504,15 @@ then
         echo "ERROR: haproxy configuration failed, exiting"
         exit 1
     fi
+fi
+
+# Clean up backgrounddelete account
+if [[ $cleanup_both == true ]]
+then
+    s3psetup --cleanup accounts
+    # Using both causes the config files to be removed and
+    # this will impact idempotency
+    # s3psetup --cleanup both
 fi
 
 # Clean up backgrounddelete account
