EOS-16875: Modify s3_setup shell script to Python - Test phase                         Changes in files: 				modified:   scripts/provisioning/s3_setup                         Description:                             s3_setup must return thr exact msg when test passes otherwise mini-provisioning pre-merge setup will fail.
Signed-off-by: pratyush-seagate <pratyush.k.khan@seagate.com>

diff --git a/scripts/provisioning/s3_setup b/scripts/provisioning/s3_setup
--- a/scripts/provisioning/s3_setup
+++ b/scripts/provisioning/s3_setup
@@ -325,14 +325,15 @@ then
     echo "INFO: Get openldap passwords from confstore.."
     get_ldap_password
 
-    s3setup test --ldappasswd $ldappasswd
-    cmd_ret=$?
+    cmd_ret=0
+    cmd_out=$(s3setup test --ldappasswd $ldappasswd) || cmd_ret=$?
 
     if [ $cmd_ret -ne 0 ];then
+        echo "ERROR:\n $cmd_out \n"
         echo "ERROR: s3setup test failed, exit."
         exit 1
     else
-        echo "PASS: s3setup test passed."
+        echo "PASS: S3-Sanity test passed."
     fi
 fi
 
